//! Initial-quantizer predictor table for the perceptual quality controller.
//!
//! GENERATED by `tools/calibrate_initial_rung.py fit` from the calibration
//! split of `test-set/quality-corpus.json`. Do not edit by hand: rerun the
//! calibration and regenerate. The controller starts its SSIMULACRA2 search
//! at the rung this table (or [`FALLBACK_LOG_FIT`]) predicts for the request.
//!
//! `global_scale` is the fixed-quantizer `VarDCT` scale (`HfMul` = 1); each
//! cell holds the geometric mean over its calibration images of the coarsest
//! scale reaching the target score, found by log-linear interpolation of
//! `ln(100 - score)` against `ln(global_scale)`.

/// One predicted starting rung: for a target score and a feature bucket, the
/// geometric-mean `global_scale` that reached the target across the bucket's
/// calibration images.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct InitialRungEntry {
    /// Target SSIMULACRA2 score this rung is calibrated for.
    pub target: f32,
    /// Luma-variance bucket index (0..=4), thresholded by [`LUMA_BUCKET_EDGES`].
    pub luma_bucket: u8,
    /// Flat-fraction bucket index (0..=2), thresholded by [`FLAT_BUCKET_EDGES`].
    pub flat_bucket: u8,
    /// Predicted fixed-quantizer `global_scale` (clamped to `1..=73728`).
    pub global_scale: u32,
    /// Number of calibration images backing this cell.
    pub support: u16,
}

/// Ascending `luma_variance_q50` bucket edges (calibration q20/40/60/80). A
/// feature's bucket is the count of edges it is greater than or equal to.
pub const LUMA_BUCKET_EDGES: [f32; 4] = [1.2599952e-07, 5.6737383e-05, 9.813392e-05, 0.00017977731];

/// Ascending `flat_fraction` bucket edges: `<0.2`, `0.2..0.6`, `>=0.6`.
pub const FLAT_BUCKET_EDGES: [f32; 2] = [0.2, 0.6];

/// Global fallback fit for cells the table does not populate:
/// `ln(global_scale) = a + b*ln(100 - target) + c*ln(luma_q50 + 1e-6) + d*flat_fraction`,
/// with `[a, b, c, d]` fitted by ordinary least squares over the calibration
/// crossings. Evaluate, exponentiate, then clamp to `1..=73728`.
pub const FALLBACK_LOG_FIT: [f64; 4] = [
    15.615602561070592,
    -1.6033739861412692,
    0.009891719405523072,
    -2.5749219514805652,
];

/// The predicted starting rungs, sorted by `(target, luma_bucket, flat_bucket)`.
pub const INITIAL_RUNG_TABLE: &[InitialRungEntry] = &[
    InitialRungEntry {
        target: 30.0,
        luma_bucket: 0,
        flat_bucket: 1,
        global_scale: 6896,
        support: 1,
    },
    InitialRungEntry {
        target: 30.0,
        luma_bucket: 0,
        flat_bucket: 2,
        global_scale: 471,
        support: 2,
    },
    InitialRungEntry {
        target: 30.0,
        luma_bucket: 1,
        flat_bucket: 1,
        global_scale: 4783,
        support: 1,
    },
    InitialRungEntry {
        target: 30.0,
        luma_bucket: 1,
        flat_bucket: 2,
        global_scale: 572,
        support: 2,
    },
    InitialRungEntry {
        target: 30.0,
        luma_bucket: 2,
        flat_bucket: 0,
        global_scale: 1690,
        support: 3,
    },
    InitialRungEntry {
        target: 30.0,
        luma_bucket: 3,
        flat_bucket: 0,
        global_scale: 1785,
        support: 2,
    },
    InitialRungEntry {
        target: 30.0,
        luma_bucket: 3,
        flat_bucket: 1,
        global_scale: 3854,
        support: 1,
    },
    InitialRungEntry {
        target: 30.0,
        luma_bucket: 4,
        flat_bucket: 0,
        global_scale: 3821,
        support: 4,
    },
    InitialRungEntry {
        target: 50.0,
        luma_bucket: 0,
        flat_bucket: 1,
        global_scale: 15154,
        support: 1,
    },
    InitialRungEntry {
        target: 50.0,
        luma_bucket: 0,
        flat_bucket: 2,
        global_scale: 801,
        support: 2,
    },
    InitialRungEntry {
        target: 50.0,
        luma_bucket: 1,
        flat_bucket: 1,
        global_scale: 10711,
        support: 1,
    },
    InitialRungEntry {
        target: 50.0,
        luma_bucket: 1,
        flat_bucket: 2,
        global_scale: 787,
        support: 2,
    },
    InitialRungEntry {
        target: 50.0,
        luma_bucket: 2,
        flat_bucket: 0,
        global_scale: 4136,
        support: 3,
    },
    InitialRungEntry {
        target: 50.0,
        luma_bucket: 3,
        flat_bucket: 0,
        global_scale: 4695,
        support: 2,
    },
    InitialRungEntry {
        target: 50.0,
        luma_bucket: 3,
        flat_bucket: 1,
        global_scale: 8391,
        support: 1,
    },
    InitialRungEntry {
        target: 50.0,
        luma_bucket: 4,
        flat_bucket: 0,
        global_scale: 10966,
        support: 4,
    },
    InitialRungEntry {
        target: 70.0,
        luma_bucket: 0,
        flat_bucket: 1,
        global_scale: 35247,
        support: 1,
    },
    InitialRungEntry {
        target: 70.0,
        luma_bucket: 0,
        flat_bucket: 2,
        global_scale: 1650,
        support: 2,
    },
    InitialRungEntry {
        target: 70.0,
        luma_bucket: 1,
        flat_bucket: 1,
        global_scale: 24427,
        support: 1,
    },
    InitialRungEntry {
        target: 70.0,
        luma_bucket: 1,
        flat_bucket: 2,
        global_scale: 1299,
        support: 2,
    },
    InitialRungEntry {
        target: 70.0,
        luma_bucket: 2,
        flat_bucket: 0,
        global_scale: 14834,
        support: 3,
    },
    InitialRungEntry {
        target: 70.0,
        luma_bucket: 3,
        flat_bucket: 0,
        global_scale: 14981,
        support: 2,
    },
    InitialRungEntry {
        target: 70.0,
        luma_bucket: 3,
        flat_bucket: 1,
        global_scale: 22939,
        support: 1,
    },
    InitialRungEntry {
        target: 70.0,
        luma_bucket: 4,
        flat_bucket: 0,
        global_scale: 30507,
        support: 4,
    },
    InitialRungEntry {
        target: 80.0,
        luma_bucket: 0,
        flat_bucket: 1,
        global_scale: 65292,
        support: 1,
    },
    InitialRungEntry {
        target: 80.0,
        luma_bucket: 0,
        flat_bucket: 2,
        global_scale: 3048,
        support: 2,
    },
    InitialRungEntry {
        target: 80.0,
        luma_bucket: 1,
        flat_bucket: 1,
        global_scale: 55021,
        support: 1,
    },
    InitialRungEntry {
        target: 80.0,
        luma_bucket: 1,
        flat_bucket: 2,
        global_scale: 2111,
        support: 2,
    },
    InitialRungEntry {
        target: 80.0,
        luma_bucket: 2,
        flat_bucket: 0,
        global_scale: 32236,
        support: 3,
    },
    InitialRungEntry {
        target: 80.0,
        luma_bucket: 3,
        flat_bucket: 0,
        global_scale: 30721,
        support: 2,
    },
    InitialRungEntry {
        target: 80.0,
        luma_bucket: 3,
        flat_bucket: 1,
        global_scale: 44354,
        support: 1,
    },
    InitialRungEntry {
        target: 80.0,
        luma_bucket: 4,
        flat_bucket: 0,
        global_scale: 49429,
        support: 4,
    },
    InitialRungEntry {
        target: 85.0,
        luma_bucket: 0,
        flat_bucket: 1,
        global_scale: 73728,
        support: 1,
    },
    InitialRungEntry {
        target: 85.0,
        luma_bucket: 0,
        flat_bucket: 2,
        global_scale: 5043,
        support: 2,
    },
    InitialRungEntry {
        target: 85.0,
        luma_bucket: 1,
        flat_bucket: 1,
        global_scale: 73728,
        support: 1,
    },
    InitialRungEntry {
        target: 85.0,
        luma_bucket: 1,
        flat_bucket: 2,
        global_scale: 3202,
        support: 2,
    },
    InitialRungEntry {
        target: 85.0,
        luma_bucket: 2,
        flat_bucket: 0,
        global_scale: 53561,
        support: 3,
    },
    InitialRungEntry {
        target: 85.0,
        luma_bucket: 3,
        flat_bucket: 0,
        global_scale: 50434,
        support: 2,
    },
    InitialRungEntry {
        target: 85.0,
        luma_bucket: 3,
        flat_bucket: 1,
        global_scale: 68744,
        support: 1,
    },
    InitialRungEntry {
        target: 85.0,
        luma_bucket: 4,
        flat_bucket: 0,
        global_scale: 66284,
        support: 4,
    },
    InitialRungEntry {
        target: 90.0,
        luma_bucket: 0,
        flat_bucket: 1,
        global_scale: 73728,
        support: 1,
    },
    InitialRungEntry {
        target: 90.0,
        luma_bucket: 0,
        flat_bucket: 2,
        global_scale: 9688,
        support: 2,
    },
    InitialRungEntry {
        target: 90.0,
        luma_bucket: 1,
        flat_bucket: 1,
        global_scale: 73728,
        support: 1,
    },
    InitialRungEntry {
        target: 90.0,
        luma_bucket: 1,
        flat_bucket: 2,
        global_scale: 9139,
        support: 2,
    },
    InitialRungEntry {
        target: 90.0,
        luma_bucket: 2,
        flat_bucket: 0,
        global_scale: 73728,
        support: 3,
    },
    InitialRungEntry {
        target: 90.0,
        luma_bucket: 3,
        flat_bucket: 0,
        global_scale: 73728,
        support: 2,
    },
    InitialRungEntry {
        target: 90.0,
        luma_bucket: 3,
        flat_bucket: 1,
        global_scale: 73728,
        support: 1,
    },
    InitialRungEntry {
        target: 90.0,
        luma_bucket: 4,
        flat_bucket: 0,
        global_scale: 73728,
        support: 4,
    },
    InitialRungEntry {
        target: 95.0,
        luma_bucket: 0,
        flat_bucket: 1,
        global_scale: 73728,
        support: 1,
    },
    InitialRungEntry {
        target: 95.0,
        luma_bucket: 0,
        flat_bucket: 2,
        global_scale: 43968,
        support: 2,
    },
    InitialRungEntry {
        target: 95.0,
        luma_bucket: 1,
        flat_bucket: 1,
        global_scale: 73728,
        support: 1,
    },
    InitialRungEntry {
        target: 95.0,
        luma_bucket: 1,
        flat_bucket: 2,
        global_scale: 73728,
        support: 2,
    },
    InitialRungEntry {
        target: 95.0,
        luma_bucket: 2,
        flat_bucket: 0,
        global_scale: 73728,
        support: 3,
    },
    InitialRungEntry {
        target: 95.0,
        luma_bucket: 3,
        flat_bucket: 0,
        global_scale: 73728,
        support: 2,
    },
    InitialRungEntry {
        target: 95.0,
        luma_bucket: 3,
        flat_bucket: 1,
        global_scale: 73728,
        support: 1,
    },
    InitialRungEntry {
        target: 95.0,
        luma_bucket: 4,
        flat_bucket: 0,
        global_scale: 73728,
        support: 4,
    },
];
