#!/usr/bin/env python3
"""Deterministic generator for the JPXL "quality-guard" corpus (PR 0).

The quality-guard corpus feeds the perceptual quality controller work. It mixes
adversarial synthetic content (text, line art, gradients, saturated colour,
tiny crops) with derivatives (low-light noise, grayscale) and real project
photographs, split into calibration / development / locked-holdout so no source
family straddles two splits.

Outputs live under ``test-set/quality-guard/`` (gitignored, per AGENTS.md §3)
and are described by ``test-set/quality-corpus.json`` — a ``jpxl.codec-corpus/1``
manifest consumed by ``JPXL/tools/codec_compare.py``.

The harness (`load_manifest` in codec_compare.py) reads each image's ``path`` as
a **binary RGB PPM (P6)** with maxval 255 or 65535 and hashes it, so every
manifest entry points at a ``.ppm`` file. Synthetic/derived fixtures also get a
canonical 8-bit (or 16-bit) sRGB PNG next to the PPM. Every fixture carries a
JSON provenance sidecar (AGENTS.md §9): source/parent + sha256 + transform for
derivatives, generator version + seed for synthetics.

Determinism: all randomness flows through ``numpy`` PRNGs seeded per fixture and
a fixed ``GENERATOR_VERSION``. The PPM raster is fully deterministic and is the
authority for the ``build --check`` idempotency test; PNG bytes are compared too
but only warned on (they can drift across Pillow/zlib versions).

Usage::

    python3 JPXL/tools/make-quality-guard-fixtures.py build
    python3 JPXL/tools/make-quality-guard-fixtures.py build --check
    python3 JPXL/tools/make-quality-guard-fixtures.py list

`build` writes fixtures + manifest. `build --check` regenerates in memory and
compares sha256 against what is on disk (fails on any PPM mismatch). `list`
prints the planned fixture table without touching disk.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import struct
import sys
import zlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

import numpy as np
from PIL import Image, ImageDraw, ImageFont

GENERATOR = "make-quality-guard-fixtures.py"
GENERATOR_VERSION = "1.0.0"
CORPUS_SCHEMA = "jpxl.codec-corpus/1"
SIDECAR_SCHEMA = "jpxl.quality-guard-fixture/1"

# Repo root = two levels up from JPXL/tools/.
REPO_ROOT = Path(__file__).resolve().parents[2]
CORPUS_DIR = REPO_ROOT / "test-set" / "quality-guard"
MANIFEST_PATH = REPO_ROOT / "test-set" / "quality-corpus.json"

SYNTHETIC_LICENSE = "MIT (synthetic, generated by this repository)"
DERIVED_LICENSE = "MIT (derivative of a project-owned image; see parent)"
PHOTO_LICENSE = "Project-owned photograph (JPXL test corpus); all rights the project's"
PHOTO_PROVENANCE = (
    "Project-owned photograph supplied with the JPXL repository under test-set/; "
    "converted PNG->P6 PPM (sRGB, 8-bit, no resampling)"
)

# --------------------------------------------------------------------------- #
# Existing source images (repo-relative). Grouped by "family" so a family is
# never placed in two splits.
# --------------------------------------------------------------------------- #
SCENES = {
    "20240501_110934": "test-set/20240501_110934.png",
    "20240502_151356": "test-set/20240502_151356.png",
    "20240502_151800": "test-set/20240502_151800.png",
    "20240502_184356": "test-set/20240502_184356.png",
    "20240502_192515": "test-set/20240502_192515.png",
    "20240503_105655": "test-set/20240503_105655.png",
    "20240503_105759": "test-set/20240503_105759.png",
}

# --------------------------------------------------------------------------- #
# Low-level encoders / hashing
# --------------------------------------------------------------------------- #


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def ppm_p6(arr: np.ndarray) -> bytes:
    """Encode an HxWx3 uint8/uint16 array as a binary P6 PPM (big-endian)."""
    if arr.ndim != 3 or arr.shape[2] != 3:
        raise ValueError(f"expected HxWx3 array, got {arr.shape}")
    height, width, _ = arr.shape
    if arr.dtype == np.uint8:
        maxval = 255
        body = np.ascontiguousarray(arr).tobytes()
    elif arr.dtype == np.uint16:
        maxval = 65535
        body = np.ascontiguousarray(arr.astype(">u2")).tobytes()
    else:
        raise ValueError(f"unsupported dtype {arr.dtype}")
    header = f"P6\n{width} {height}\n{maxval}\n".encode("ascii")
    return header + body


def png_encode(arr: np.ndarray) -> bytes:
    """Deterministically encode HxWx3 uint8 (Pillow) or uint16 (hand-rolled)."""
    if arr.dtype == np.uint8:
        buffer = io.BytesIO()
        Image.fromarray(np.ascontiguousarray(arr)).save(
            buffer, format="PNG", optimize=False, compress_level=6
        )
        return buffer.getvalue()
    if arr.dtype == np.uint16:
        return _png16(arr)
    raise ValueError(f"unsupported dtype {arr.dtype}")


def _png16(arr: np.ndarray) -> bytes:
    """Minimal deterministic 16-bit RGB PNG (colour type 2, bit depth 16)."""
    height, width, _ = arr.shape
    be = np.ascontiguousarray(arr.astype(">u2"))
    rows = bytearray()
    line_bytes = width * 3 * 2
    flat = be.tobytes()
    for y in range(height):
        rows.append(0)  # filter type 0 (None)
        rows.extend(flat[y * line_bytes : (y + 1) * line_bytes])

    def chunk(kind: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + kind
            + data
            + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
        )

    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 16, 2, 0, 0, 0)
    idat = zlib.compress(bytes(rows), 6)
    return sig + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b"")


# --------------------------------------------------------------------------- #
# Colour-space helpers
# --------------------------------------------------------------------------- #


def srgb_to_linear(x: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=np.float64)
    return np.where(x <= 0.04045, x / 12.92, ((x + 0.055) / 1.055) ** 2.4)


def linear_to_srgb(x: np.ndarray) -> np.ndarray:
    x = np.clip(np.asarray(x, dtype=np.float64), 0.0, 1.0)
    return np.where(x <= 0.0031308, x * 12.92, 1.055 * (x ** (1 / 2.4)) - 0.055)


def to_u8(x: np.ndarray) -> np.ndarray:
    return np.clip(np.rint(x), 0, 255).astype(np.uint8)


def load_rgb(rel_path: str) -> np.ndarray:
    with Image.open(REPO_ROOT / rel_path) as im:
        return np.asarray(im.convert("RGB"), dtype=np.uint8).copy()


# --------------------------------------------------------------------------- #
# Fixture model
# --------------------------------------------------------------------------- #


@dataclass
class Fixture:
    fixture_id: str
    klass: str
    split: str  # calibration | development | holdout
    subdir: str
    build: Callable[[], np.ndarray]  # returns HxWx3 uint8 or uint16
    provenance: str
    license: str
    kind: str  # synthetic | derived | source
    write_png: bool = True
    seed: int | None = None
    parent: dict[str, Any] | None = None
    transform: str | None = None
    notes: str | None = None
    # Filled during realisation:
    _array: np.ndarray | None = field(default=None, repr=False)

    @property
    def array(self) -> np.ndarray:
        if self._array is None:
            self._array = self.build()
        return self._array

    def dims(self) -> tuple[int, int, int]:
        h, w, _ = self.array.shape
        depth = 8 if self.array.dtype == np.uint8 else 16
        return w, h, depth

    def ppm_rel(self) -> str:
        return f"quality-guard/{self.subdir}/{self.fixture_id}.ppm"

    def png_rel(self) -> str:
        return f"quality-guard/{self.subdir}/{self.fixture_id}.png"

    def sidecar_rel(self) -> str:
        return f"quality-guard/{self.subdir}/{self.fixture_id}.json"


# --------------------------------------------------------------------------- #
# Synthetic content builders
# --------------------------------------------------------------------------- #

WORDS = (
    "the quick brown fox jumps over a lazy dog while bright vector glyphs "
    "render crisp anti aliased edges across a flat neutral field of pixels "
    "quality guard corpus text screenshot line art gradient saturated tiny "
    "encoder decoder perceptual metric luma chroma sharp boundary contrast "
    "screenshot document paragraph heading footer sidebar button toolbar icon"
).split()

TEXT_COLORS = [
    (0, 0, 0),
    (176, 32, 32),
    (32, 96, 176),
    (24, 128, 64),
    (128, 64, 160),
    (192, 96, 16),
]


def _paragraph(rng: np.random.Generator, n_words: int) -> str:
    idx = rng.integers(0, len(WORDS), size=n_words)
    words = [WORDS[i] for i in idx]
    words[0] = words[0].capitalize()
    return " ".join(words) + "."


def _wrap(draw: ImageDraw.ImageDraw, text: str, font, max_width: int) -> list[str]:
    lines: list[str] = []
    current = ""
    for word in text.split():
        trial = f"{current} {word}".strip()
        if draw.textlength(trial, font=font) <= max_width or not current:
            current = trial
        else:
            lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def build_text(width: int, height: int, seed: int, dark: bool) -> np.ndarray:
    rng = np.random.default_rng(seed)
    bg = (18, 20, 24) if dark else (255, 255, 255)
    img = Image.new("RGB", (width, height), bg)
    draw = ImageDraw.Draw(img)
    body = ImageFont.load_default(size=20)
    head = ImageFont.load_default(size=32)
    margin = 40
    y = margin
    draw.text((margin, y), _paragraph(rng, 4), font=head,
              fill=(235, 235, 235) if dark else (10, 10, 10))
    y += 52
    while y < height - margin:
        color = TEXT_COLORS[int(rng.integers(0, len(TEXT_COLORS)))]
        if dark:
            color = tuple(min(255, c + 110) for c in color)
        para = _paragraph(rng, int(rng.integers(24, 48)))
        for line in _wrap(draw, para, body, width - 2 * margin):
            if y >= height - margin:
                break
            draw.text((margin, y), line, font=body, fill=color)
            y += 26
        y += 14
    return np.asarray(img, dtype=np.uint8).copy()


def build_text_ui(width: int, height: int, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    img = Image.new("RGB", (width, height), (244, 246, 249))
    draw = ImageDraw.Draw(img)
    small = ImageFont.load_default()  # 5x8 bitmap default
    label = ImageFont.load_default(size=16)
    # Top toolbar with thin separator lines.
    draw.rectangle([0, 0, width, 48], fill=(38, 44, 56))
    for i in range(6):
        x = 16 + i * 90
        draw.rectangle([x, 12, x + 74, 36], outline=(120, 132, 150), width=1)
        draw.text((x + 8, 18), WORDS[i % len(WORDS)][:8], font=small, fill=(230, 232, 236))
    # Sidebar with 1-px grid lines.
    draw.rectangle([0, 48, 180, height], fill=(228, 231, 236))
    for row in range(18):
        yy = 60 + row * 30
        draw.line([(0, yy), (180, yy)], fill=(200, 204, 212), width=1)
        draw.text((12, yy + 6), WORDS[(row + 3) % len(WORDS)], font=small, fill=(60, 66, 78))
    # Content cards.
    for _ in range(10):
        x0 = int(rng.integers(200, width - 260))
        y0 = int(rng.integers(64, height - 140))
        w = int(rng.integers(160, 240))
        h = int(rng.integers(80, 120))
        fill = tuple(int(c) for c in rng.integers(235, 255, size=3))
        draw.rectangle([x0, y0, x0 + w, y0 + h], fill=fill, outline=(150, 156, 168), width=1)
        draw.line([(x0 + 10, y0 + 28), (x0 + w - 10, y0 + 28)], fill=(120, 126, 138), width=1)
        draw.text((x0 + 10, y0 + 8), _paragraph(rng, 2)[:24], font=label, fill=(30, 34, 42))
    return np.asarray(img, dtype=np.uint8).copy()


def build_line_art(width: int, height: int, seed: int, anti_alias: bool) -> np.ndarray:
    rng = np.random.default_rng(seed)
    ss = 4 if anti_alias else 1
    W, H = width * ss, height * ss
    img = Image.new("RGB", (W, H), (250, 250, 248))
    draw = ImageDraw.Draw(img)
    # Circles.
    for _ in range(14):
        cx, cy = int(rng.integers(0, W)), int(rng.integers(0, H))
        r = int(rng.integers(20 * ss, 120 * ss))
        col = tuple(int(c) for c in rng.integers(0, 200, size=3))
        draw.ellipse([cx - r, cy - r, cx + r, cy + r], outline=col, width=max(1, ss))
    # Polygons.
    for _ in range(8):
        n = int(rng.integers(3, 7))
        pts = [(int(rng.integers(0, W)), int(rng.integers(0, H))) for _ in range(n)]
        col = tuple(int(c) for c in rng.integers(0, 200, size=3))
        draw.polygon(pts, outline=col)
    # Thin diagonal line fan.
    for i in range(0, W, 24 * ss):
        draw.line([(i, 0), (0, i)], fill=(40, 40, 40), width=max(1, ss))
    if anti_alias and ss > 1:
        img = img.resize((width, height), Image.LANCZOS)
    return np.asarray(img, dtype=np.uint8).copy()


def build_hatch(width: int, height: int, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    img = Image.new("RGB", (width, height), (255, 255, 255))
    draw = ImageDraw.Draw(img)
    spacing = 6
    for x in range(-height, width, spacing):
        draw.line([(x, 0), (x + height, height)], fill=(20, 20, 20), width=1)
    for x in range(0, width + height, spacing * 2):
        draw.line([(x, 0), (x - height, height)], fill=(90, 90, 90), width=1)
    # A few solid reference squares to mix flat and hatched regions.
    for _ in range(5):
        x0 = int(rng.integers(0, width - 120))
        y0 = int(rng.integers(0, height - 120))
        col = tuple(int(c) for c in rng.integers(0, 255, size=3))
        draw.rectangle([x0, y0, x0 + 100, y0 + 100], fill=col)
    return np.asarray(img, dtype=np.uint8).copy()


def build_gradient(width: int, height: int, mode: str, seed: int, depth: int = 8) -> np.ndarray:
    rng = np.random.default_rng(seed)
    yy, xx = np.mgrid[0:height, 0:width].astype(np.float64)
    if mode == "horizontal":
        t = xx / max(1, width - 1)
        r, g, b = t, 0.5 * np.ones_like(t), 1.0 - t
    elif mode == "vertical":
        t = yy / max(1, height - 1)
        r, g, b = 0.2 + 0.6 * t, t, 0.9 - 0.5 * t
    elif mode == "radial":
        cx, cy = width / 2.0, height / 2.0
        d = np.sqrt((xx - cx) ** 2 + (yy - cy) ** 2)
        t = d / d.max()
        r, g, b = 1.0 - t, 0.3 + 0.4 * t, t
    elif mode == "sky":
        # Low-amplitude near-blue sky ramp with slight noise (banding stress).
        t = yy / max(1, height - 1)
        r = 0.42 + 0.06 * t
        g = 0.58 + 0.05 * t
        b = 0.80 - 0.04 * t
        noise = rng.normal(0.0, 1.2 / 255.0, size=(height, width))
        r, g, b = r + noise, g + noise, b + noise
    else:
        raise ValueError(f"unknown gradient mode {mode}")
    rgb = np.clip(np.stack([r, g, b], axis=-1), 0.0, 1.0)
    if depth == 16:
        return np.rint(rgb * 65535.0).astype(np.uint16)
    return to_u8(rgb * 255.0)


def build_saturated(width: int, height: int, seed: int, soft: bool) -> np.ndarray:
    primaries = [
        (255, 0, 0), (0, 255, 0), (0, 0, 255),
        (0, 255, 255), (255, 0, 255), (255, 255, 0),
        (255, 255, 255), (0, 0, 0),
    ]
    cols = 4
    rows = 2
    cw, ch = width // cols, height // rows
    arr = np.zeros((height, width, 3), dtype=np.uint8)
    for idx, color in enumerate(primaries):
        rr, cc = divmod(idx, cols)
        y0, x0 = rr * ch, cc * cw
        arr[y0 : y0 + ch, x0 : x0 + cw] = color
    if soft:
        blurred = np.asarray(
            Image.fromarray(arr).filter(
                __import__("PIL.ImageFilter", fromlist=["GaussianBlur"]).GaussianBlur(3.5)
            ),
            dtype=np.uint8,
        )
        arr = blurred.copy()
    return arr


def crop(arr: np.ndarray, w: int, h: int, ox: int, oy: int) -> np.ndarray:
    H, W, _ = arr.shape
    ox = max(0, min(ox, W - w))
    oy = max(0, min(oy, H - h))
    return np.ascontiguousarray(arr[oy : oy + h, ox : ox + w])


def build_grayscale(arr: np.ndarray) -> np.ndarray:
    lin = srgb_to_linear(arr.astype(np.float64) / 255.0)
    y = 0.2126 * lin[..., 0] + 0.7152 * lin[..., 1] + 0.0722 * lin[..., 2]
    srgb = linear_to_srgb(y)
    g = to_u8(srgb * 255.0)
    return np.repeat(g[..., None], 3, axis=2)


def build_lowlight(arr: np.ndarray, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    lin = srgb_to_linear(arr.astype(np.float64) / 255.0) * 0.25
    scale = 500.0  # photon-count scale for Poisson shot noise
    shot = rng.poisson(np.clip(lin, 0.0, None) * scale) / scale
    read = rng.normal(0.0, 0.006, size=lin.shape)  # sensor read noise (linear)
    noisy = np.clip(shot + read, 0.0, 1.0)
    return to_u8(linear_to_srgb(noisy) * 255.0)


# --------------------------------------------------------------------------- #
# Fixture registry
# --------------------------------------------------------------------------- #


def _synth(fid, klass, split, subdir, fn, seed, provenance, notes=None) -> Fixture:
    return Fixture(
        fixture_id=fid, klass=klass, split=split, subdir=subdir, build=fn,
        provenance=provenance, license=SYNTHETIC_LICENSE, kind="synthetic",
        write_png=True, seed=seed, notes=notes,
    )


def _derived(fid, klass, split, subdir, fn, parent_rel, transform, seed=None) -> Fixture:
    parent_sha = sha256_file(REPO_ROOT / parent_rel)
    return Fixture(
        fixture_id=fid, klass=klass, split=split, subdir=subdir, build=fn,
        provenance=f"Derived from {parent_rel} ({transform})",
        license=DERIVED_LICENSE, kind="derived", write_png=True, seed=seed,
        parent={"path": parent_rel, "sha256": parent_sha}, transform=transform,
    )


def _source(fid, klass, split, subdir, src_rel) -> Fixture:
    return Fixture(
        fixture_id=fid, klass=klass, split=split, subdir=subdir,
        build=lambda p=src_rel: load_rgb(p),
        provenance=PHOTO_PROVENANCE, license=PHOTO_LICENSE, kind="source",
        write_png=False,
        parent={"path": src_rel, "sha256": sha256_file(REPO_ROOT / src_rel)},
        transform="decode PNG -> P6 PPM, sRGB 8-bit, no resampling",
    )


def registry() -> list[Fixture]:
    fx: list[Fixture] = []

    # ---- text-screenshot (synthetic): two sizes, white/dark/UI/mixed ------- #
    fx.append(_synth("text-screenshot-white-1024x768", "text-screenshot", "calibration",
                     "synthetic/text-screenshot", lambda: build_text(1024, 768, 1001, dark=False),
                     1001, "Rendered black+coloured paragraphs on white (Pillow default font)"))
    fx.append(_synth("text-screenshot-ui-1920x1080", "text-screenshot", "calibration",
                     "synthetic/text-screenshot", lambda: build_text_ui(1920, 1080, 1002),
                     1002, "UI mock: toolbar/sidebar rectangles, 1-px lines, small bitmap text"))
    fx.append(_synth("text-screenshot-dark-1024x768", "text-screenshot", "development",
                     "synthetic/text-screenshot", lambda: build_text(1024, 768, 1003, dark=True),
                     1003, "Rendered light+coloured paragraphs on dark background"))
    fx.append(_synth("text-screenshot-mixed-1920x1080", "text-screenshot", "development",
                     "synthetic/text-screenshot", lambda: build_text(1920, 1080, 1004, dark=False),
                     1004, "Dense mixed-colour paragraphs on white, large canvas"))
    fx.append(_synth("text-screenshot-holdout-1600x900", "text-screenshot", "holdout",
                     "synthetic/text-screenshot", lambda: build_text(1600, 900, 19001, dark=False),
                     19001, "Holdout paragraphs on white, fresh seed"))

    # ---- line-art (synthetic) ---------------------------------------------- #
    fx.append(_synth("line-art-aa-shapes-1024x1024", "line-art", "calibration",
                     "synthetic/line-art", lambda: build_line_art(1024, 1024, 2001, anti_alias=True),
                     2001, "Anti-aliased vector circles/polygons/diagonals (4x supersample)"))
    fx.append(_synth("line-art-hatch-768x768", "line-art", "calibration",
                     "synthetic/line-art", lambda: build_hatch(768, 768, 2002),
                     2002, "Thin 1-px hatch patterns plus flat reference squares"))
    fx.append(_synth("line-art-hard-shapes-1024x1024", "line-art", "development",
                     "synthetic/line-art", lambda: build_line_art(1024, 1024, 2003, anti_alias=False),
                     2003, "Non-anti-aliased hard-edge vector shapes"))
    fx.append(_synth("line-art-diagonals-800x600", "line-art", "development",
                     "synthetic/line-art", lambda: build_line_art(800, 600, 2004, anti_alias=False),
                     2004, "Non-anti-aliased thin diagonal fan and outlines"))
    fx.append(_synth("line-art-holdout-900x900", "line-art", "holdout",
                     "synthetic/line-art", lambda: build_line_art(900, 900, 29001, anti_alias=True),
                     29001, "Holdout anti-aliased vector shapes, fresh seed"))

    # ---- gradient (synthetic) ---------------------------------------------- #
    fx.append(_synth("gradient-horizontal-1024x512", "gradient", "calibration",
                     "synthetic/gradient", lambda: build_gradient(1024, 512, "horizontal", 3001),
                     3001, "Smooth 8-bit horizontal RGB ramp"))
    fx.append(_synth("gradient-radial-768x768", "gradient", "calibration",
                     "synthetic/gradient", lambda: build_gradient(768, 768, "radial", 3002),
                     3002, "Smooth 8-bit radial ramp"))
    fx.append(_synth("gradient-16bit-1024x512", "gradient", "calibration",
                     "synthetic/gradient", lambda: build_gradient(1024, 512, "horizontal", 3003, depth=16),
                     3003, "16-bit horizontal ramp (P6 maxval 65535, 16-bit PNG)"))
    fx.append(_synth("gradient-vertical-512x1024", "gradient", "development",
                     "synthetic/gradient", lambda: build_gradient(512, 1024, "vertical", 3004),
                     3004, "Smooth 8-bit vertical RGB ramp"))
    fx.append(_synth("gradient-sky-noise-1024x512", "gradient", "development",
                     "synthetic/gradient", lambda: build_gradient(1024, 512, "sky", 3005),
                     3005, "Low-amplitude sky-like gradient with slight seeded noise (banding stress)"))
    fx.append(_synth("gradient-holdout-radial-700x700", "gradient", "holdout",
                     "synthetic/gradient", lambda: build_gradient(700, 700, "radial", 39001),
                     39001, "Holdout radial ramp, fresh seed"))

    # ---- saturated (synthetic + one photo crop) ---------------------------- #
    fx.append(_synth("saturated-primaries-hard-512x512", "saturated", "calibration",
                     "synthetic/saturated", lambda: build_saturated(512, 512, 4001, soft=False),
                     4001, "Fully saturated primaries/secondaries, sharp boundaries"))
    fx.append(_synth("saturated-primaries-soft-512x512", "saturated", "development",
                     "synthetic/saturated", lambda: build_saturated(512, 512, 4002, soft=True),
                     4002, "Fully saturated primaries/secondaries, soft (blurred) boundaries"))
    fx.append(_synth("saturated-holdout-640x480", "saturated", "holdout",
                     "synthetic/saturated", lambda: build_saturated(640, 480, 49001, soft=False),
                     49001, "Holdout saturated patches, fresh seed"))
    # Saturated-colour-rich crop of a calibration-family photo (203230).
    fx.append(_derived(
        "saturated-photo-203230-crop-512x512", "saturated", "calibration",
        "synthetic/saturated",
        lambda: crop(load_rgb("test-set/test-set-4mp/20260606_203230_4mp.png"), 512, 512, 900, 700),
        "test-set/test-set-4mp/20260606_203230_4mp.png",
        "centre-ish 512x512 crop at (x=900,y=700), sRGB 8-bit, no resampling"))

    # ---- gradient/line-art done; tiny crops (exempt from 256x256) ---------- #
    tiny_sizes = [(7, 7), (8, 8), (16, 16), (33, 20), (64, 64)]
    # Calibration tiny crops from calibration scene 20240501_110934.
    cal_scene = "test-set/20240501_110934.png"
    for (w, h) in [(7, 7), (16, 16), (64, 64)]:
        fx.append(_derived(
            f"tiny-{w}x{h}-cal", "tiny", "calibration", "synthetic/tiny",
            (lambda p=cal_scene, w=w, h=h: crop(load_rgb(p), w, h, 400, 300)),
            cal_scene, f"{w}x{h} crop at (x=400,y=300), sRGB 8-bit"))
    # Development tiny crops from development scene 20240503_105655.
    dev_scene = "test-set/20240503_105655.png"
    for (w, h) in [(8, 8), (33, 20)]:
        fx.append(_derived(
            f"tiny-{w}x{h}-dev", "tiny", "development", "synthetic/tiny",
            (lambda p=dev_scene, w=w, h=h: crop(load_rgb(p), w, h, 500, 350)),
            dev_scene, f"{w}x{h} crop at (x=500,y=350), sRGB 8-bit"))
    # Holdout tiny crop from holdout-family photo 201839_4mp.
    fx.append(_derived(
        "tiny-64x64-holdout", "tiny", "holdout", "synthetic/tiny",
        lambda: crop(load_rgb("test-set/test-set-4mp/20260606_201839_4mp.png"), 64, 64, 1200, 900),
        "test-set/test-set-4mp/20260606_201839_4mp.png",
        "64x64 crop at (x=1200,y=900), sRGB 8-bit"))
    _ = tiny_sizes  # documented full set (7x7,8x8,16x16,33x20,64x64) spread across splits

    # ---- noise-lowlight (derived, development scene only) ------------------- #
    fx.append(_derived(
        "noise-lowlight-184356-1024x768", "noise-lowlight", "development",
        "derived/noise-lowlight",
        lambda: build_lowlight(load_rgb("test-set/20240502_184356.png"), 5001),
        "test-set/20240502_184356.png",
        "linear-light x0.25 darken, then seeded Poisson(scale=500)+Gaussian(sigma=0.006) noise, re-encode sRGB 8-bit",
        seed=5001))

    # ---- grayscale (derived) ----------------------------------------------- #
    fx.append(_derived(
        "grayscale-scene-192515-1024x768", "grayscale", "development",
        "derived/grayscale",
        lambda: build_grayscale(load_rgb("test-set/20240502_192515.png")),
        "test-set/20240502_192515.png",
        "Rec.709 linear-light luma, re-encode sRGB, replicated to R=G=B"))
    fx.append(_derived(
        "grayscale-photo-203230-crop-1024x1024", "grayscale", "calibration",
        "derived/grayscale",
        lambda: build_grayscale(crop(load_rgb("test-set/test-set-4mp/20260606_203230_4mp.png"),
                                     1024, 1024, 700, 400)),
        "test-set/test-set-4mp/20260606_203230_4mp.png",
        "1024x1024 crop at (x=700,y=400) -> Rec.709 linear-light luma -> sRGB, R=G=B"))

    # ---- real photographs (source conversions) ----------------------------- #
    # Calibration: scenes + 203230 family (mid/mid2/large anchors).
    for stem in ("20240501_110934", "20240502_151356", "20240502_151800"):
        fx.append(_source(f"scene-{stem}", "photo-scene", "calibration", "sources", SCENES[stem]))
    fx.append(_source("photo-203230-mid-2400x1800", "photo", "calibration", "sources",
                      "test-set/test-set-4mp/20260606_203230_4mp.png"))
    fx.append(_source("photo-203230-mid2-2832x2124", "photo", "calibration", "sources",
                      "test-set/test-set-4mp/20260606_203230_6mp.png"))
    fx.append(_source("photo-203230-large-4000x3000", "photo", "calibration", "sources",
                      "test-set/test-set-large/20260606_203230_result.png"))

    # Development: scenes only (no test-set photo family lands in development).
    for stem in ("20240502_184356", "20240502_192515", "20240503_105655", "20240503_105759"):
        fx.append(_source(f"scene-{stem}", "photo-scene", "development", "sources", SCENES[stem]))

    # Locked holdout: 201839 family (one-12mp == large) + remaining large families.
    fx.append(_source("photo-201839-mid-2400x1800", "photo", "holdout", "sources",
                      "test-set/test-set-4mp/20260606_201839_4mp.png"))
    fx.append(_source("photo-201839-mid2-2832x2124", "photo", "holdout", "sources",
                      "test-set/test-set-4mp/20260606_201839_6mp.png"))
    fx.append(_source("photo-201839-large-4000x3000", "photo", "holdout", "sources",
                      "test-set/one-12mp/20260606_201839_result.png"))
    for stem in ("20260606_150624", "20260606_154651", "20260607_155040",
                 "20260607_155124", "20260607_155515"):
        fx.append(_source(f"photo-large-{stem}", "photo", "holdout", "sources",
                          f"test-set/test-set-large/{stem}_result.png"))

    return fx


# --------------------------------------------------------------------------- #
# Manifest / sidecar assembly
# --------------------------------------------------------------------------- #


def size_bucket(w: int, h: int) -> str:
    n = w * h
    if n < 256 * 256:
        return "tiny"
    if n <= 1024 * 1024:
        return "small"
    if n <= 3_000_000:
        return "medium"
    if n <= 12_000_000:
        return "large"
    return "xlarge"


def sidecar_for(fx: Fixture, ppm_sha: str, png_sha: str | None) -> dict[str, Any]:
    w, h, depth = fx.dims()
    doc: dict[str, Any] = {
        "schema": SIDECAR_SCHEMA,
        "id": fx.fixture_id,
        "class": fx.klass,
        "split": fx.split,
        "kind": fx.kind,
        "width": w,
        "height": h,
        "bit_depth": depth,
        "license": fx.license,
        "provenance": fx.provenance,
        "ppm": {"path": fx.ppm_rel(), "sha256": ppm_sha, "maxval": 255 if depth == 8 else 65535},
        "regenerate": f"python3 JPXL/tools/{GENERATOR} build",
        "check": f"python3 JPXL/tools/{GENERATOR} build --check",
    }
    if png_sha is not None:
        doc["png"] = {"path": fx.png_rel(), "sha256": png_sha}
    if fx.kind == "synthetic":
        doc["generator"] = {"tool": GENERATOR, "version": GENERATOR_VERSION, "seed": fx.seed}
    if fx.parent is not None:
        doc["parent"] = fx.parent
        doc["transform"] = fx.transform
        if fx.seed is not None:
            doc["generator"] = {"tool": GENERATOR, "version": GENERATOR_VERSION, "seed": fx.seed}
    if fx.notes:
        doc["notes"] = fx.notes
    return doc


def manifest_entry(fx: Fixture, ppm_sha: str) -> dict[str, Any]:
    w, h, depth = fx.dims()
    return {
        "id": fx.fixture_id,
        "path": fx.ppm_rel(),
        "sha256": ppm_sha,
        "strata": [fx.klass, fx.split, size_bucket(w, h)],
        "split": fx.split,
        "class": fx.klass,
        "kind": fx.kind,
        "bit_depth": depth,
        "license": fx.license,
        "provenance": fx.provenance,
        "sidecar": fx.sidecar_rel(),
    }


def realise(fx: Fixture) -> tuple[bytes, bytes | None]:
    """Return (ppm_bytes, png_bytes|None) for a fixture."""
    arr = fx.array
    ppm = ppm_p6(arr)
    png = png_encode(arr) if fx.write_png else None
    return ppm, png


# --------------------------------------------------------------------------- #
# Commands
# --------------------------------------------------------------------------- #


def cmd_build(check: bool) -> int:
    fixtures = registry()
    # Duplicate-id guard.
    ids = [f.fixture_id for f in fixtures]
    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        print(f"ERROR: duplicate fixture ids: {sorted(dupes)}", file=sys.stderr)
        return 2

    manifest_images: list[dict[str, Any]] = []
    ppm_mismatch = 0
    png_mismatch = 0
    written = 0
    for fx in fixtures:
        ppm, png = realise(fx)
        ppm_sha = sha256_bytes(ppm)
        png_sha = sha256_bytes(png) if png is not None else None
        ppm_path = REPO_ROOT / "test-set" / fx.ppm_rel()
        png_path = REPO_ROOT / "test-set" / fx.png_rel()
        side_path = REPO_ROOT / "test-set" / fx.sidecar_rel()
        entry = manifest_entry(fx, ppm_sha)
        manifest_images.append(entry)

        if check:
            if not ppm_path.is_file():
                print(f"MISSING ppm: {fx.ppm_rel()}", file=sys.stderr)
                ppm_mismatch += 1
                continue
            on_disk = sha256_file(ppm_path)
            if on_disk != ppm_sha:
                print(f"PPM MISMATCH {fx.fixture_id}: disk={on_disk} regen={ppm_sha}", file=sys.stderr)
                ppm_mismatch += 1
            if png is not None and png_path.is_file():
                if sha256_file(png_path) != png_sha:
                    print(f"png differs (non-fatal, env-dependent) {fx.fixture_id}", file=sys.stderr)
                    png_mismatch += 1
        else:
            ppm_path.parent.mkdir(parents=True, exist_ok=True)
            ppm_path.write_bytes(ppm)
            if png is not None:
                png_path.write_bytes(png)
            side_path.write_text(
                json.dumps(sidecar_for(fx, ppm_sha, png_sha), indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            written += 1
        # Free memory for large photos.
        fx._array = None

    manifest = {
        "schema": CORPUS_SCHEMA,
        "generator": {"tool": GENERATOR, "version": GENERATOR_VERSION},
        "description": "JPXL quality-guard corpus (PR 0): calibration/development/locked-holdout "
                       "splits for the perceptual quality controller. Paths are P6 PPM inputs for "
                       "JPXL/tools/codec_compare.py; each has a sibling sidecar and (for synthetic/"
                       "derived fixtures) a canonical PNG.",
        "splits": ["calibration", "development", "holdout"],
        "images": manifest_images,
    }

    if check:
        if ppm_mismatch:
            print(f"CHECK FAILED: {ppm_mismatch} PPM mismatch(es), {png_mismatch} png diff(s)", file=sys.stderr)
            return 1
        # Verify the on-disk manifest matches the regenerated one (ignoring nothing).
        if MANIFEST_PATH.is_file():
            disk_manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
            if disk_manifest.get("images") != manifest_images:
                print("CHECK FAILED: manifest images drifted from regenerated set", file=sys.stderr)
                return 1
        print(f"CHECK OK: {len(fixtures)} fixtures reproduce identical PPM sha256"
              + (f" ({png_mismatch} png byte-diffs, non-fatal)" if png_mismatch else ""))
        return 0

    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    print(f"wrote {written} fixtures under {CORPUS_DIR}")
    print(f"wrote manifest {MANIFEST_PATH} with {len(manifest_images)} images")
    _print_summary(fixtures)
    return 0


def _print_summary(fixtures: list[Fixture]) -> None:
    from collections import Counter
    by_split = Counter(f.split for f in fixtures)
    by_class = Counter(f.klass for f in fixtures)
    print("\nsplit counts:", dict(by_split))
    print("class counts:", dict(by_class))


def cmd_list() -> int:
    fixtures = registry()
    print(f"{'id':44} {'class':16} {'split':12} {'kind':10}")
    for fx in fixtures:
        print(f"{fx.fixture_id:44} {fx.klass:16} {fx.split:12} {fx.kind:10}")
    _print_summary(fixtures)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    build = sub.add_parser("build", help="write fixtures + manifest")
    build.add_argument("--check", action="store_true",
                       help="regenerate and compare sha256 instead of writing (idempotency test)")
    sub.add_parser("list", help="print planned fixture table without touching disk")
    args = parser.parse_args(argv)
    if args.command == "build":
        return cmd_build(args.check)
    if args.command == "list":
        return cmd_list()
    parser.error("unknown command")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
