# Build and install the black-box reference decoders JPXL grades itself against
# on Windows (MinGW via MSYS2).
#
# Counterpart of tools/setup-oracles.sh. Prefer that script on Unix.
#
#   djxl / cjxl / jxlinfo   built from the sibling libjxl checkout with CMake+Ninja
#   jxl-oxide              installed with `cargo install jxl-oxide-cli --locked`
#
# Binaries land in tools/oracle-bin/ as *.exe, with MinGW runtime DLLs beside
# them so tests do not need MSYS on PATH. Provenance goes to PINNED_REVISIONS.txt.
#
# IMPORTANT (clean room): libjxl is a BLACK BOX. This script builds it; nobody
# reads its source.
#
# Usage (from JPXL/):
#   powershell -File tools/setup-oracles.ps1
# Env:
#   JPXL_LIBJXL_DIR   override libjxl checkout
#   JPXL_JOBS         parallel build jobs (default 8)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$jpxlRoot = Split-Path -Parent $scriptDir
$repoRoot = Split-Path -Parent $jpxlRoot
$libjxlDir = if ($env:JPXL_LIBJXL_DIR) { $env:JPXL_LIBJXL_DIR } else { Join-Path $repoRoot "libjxl" }
$buildDir = Join-Path $libjxlDir "build-win"
$oracleBin = Join-Path $scriptDir "oracle-bin"
$jobs = if ($env:JPXL_JOBS) { [int]$env:JPXL_JOBS } else { 8 }

$mingwBin = "C:\msys64\mingw64\bin"
if (-not (Test-Path (Join-Path $mingwBin "gcc.exe"))) {
    Write-Error "MinGW gcc not found at $mingwBin — install MSYS2 mingw-w64-x86_64-toolchain"
}
$env:PATH = "$mingwBin;C:\msys64\usr\bin;" + $env:PATH

function Log($msg) { Write-Host "==> $msg" }

New-Item -ItemType Directory -Force -Path $oracleBin | Out-Null

# ---------------------------------------------------------------- libjxl ----
if (-not (Test-Path $libjxlDir)) {
    Write-Error "no libjxl checkout at $libjxlDir"
}

$highway = Join-Path $libjxlDir "third_party\highway\CMakeLists.txt"
if (-not (Test-Path $highway)) {
    Log "initialising libjxl third_party submodules"
    git -C $libjxlDir submodule update --init --recursive third_party
}

Log "configuring libjxl in $buildDir"
$cmakeFlags = @(
    "-S", $libjxlDir, "-B", $buildDir, "-G", "Ninja",
    "-DCMAKE_BUILD_TYPE=Release",
    "-DCMAKE_C_COMPILER=gcc",
    "-DCMAKE_CXX_COMPILER=g++",
    "-DBUILD_TESTING=OFF",
    "-DJPEGXL_ENABLE_BENCHMARK=OFF",
    "-DJPEGXL_ENABLE_EXAMPLES=OFF",
    "-DJPEGXL_ENABLE_MANPAGES=OFF",
    "-DJPEGXL_ENABLE_PLUGINS=OFF",
    "-DJPEGXL_ENABLE_DOXYGEN=OFF",
    "-DJPEGXL_ENABLE_JNI=OFF",
    "-DJPEGXL_ENABLE_SJPEG=OFF",
    "-DJPEGXL_ENABLE_OPENEXR=OFF",
    "-DBUILD_SHARED_LIBS=OFF"
)
& cmake @cmakeFlags
if ($LASTEXITCODE -ne 0) { Write-Error "cmake configure failed" }

Log "building djxl, cjxl, jxlinfo with $jobs jobs"
& cmake --build $buildDir --target djxl,cjxl,jxlinfo -j $jobs
if ($LASTEXITCODE -ne 0) { Write-Error "cmake build failed" }

$toolsDir = Join-Path $buildDir "tools"
foreach ($tool in @("djxl", "cjxl", "jxlinfo")) {
    $src = Join-Path $toolsDir "$tool.exe"
    if (-not (Test-Path $src)) { Write-Error "missing $src" }
    Copy-Item -Force $src (Join-Path $oracleBin "$tool.exe")
    Log "installed $tool.exe"
}

# Runtime DLLs (static libjxl still links the MinGW C++ runtime dynamically).
foreach ($dll in @(
    "libgcc_s_seh-1.dll", "libstdc++-6.dll", "libwinpthread-1.dll",
    "libssp-0.dll", "zlib1.dll", "libpng16-16.dll", "libjpeg-8.dll", "libgif-7.dll"
)) {
    $from = Join-Path $mingwBin $dll
    if (Test-Path $from) {
        Copy-Item -Force $from $oracleBin
    }
}

# ------------------------------------------------------------- jxl-oxide ----
$oxide = Join-Path $env:USERPROFILE ".cargo\bin\jxl-oxide.exe"
if (-not (Test-Path $oxide)) {
    Log "installing jxl-oxide-cli"
    cargo install jxl-oxide-cli --locked
}

# ------------------------------------------------------------ provenance ----
$rev = git -C $libjxlDir rev-parse HEAD
$desc = git -C $libjxlDir describe --tags --always --dirty 2>$null
$djxlv = & (Join-Path $oracleBin "djxl.exe") --version 2>&1 | Select-Object -First 1
$cjxlv = & (Join-Path $oracleBin "cjxl.exe") --version 2>&1 | Select-Object -First 1
$oxidev = if (Test-Path $oxide) { & $oxide --version 2>&1 | Select-Object -First 1 } else { "not installed" }
$date = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

@"
# JPXL oracle provenance
# Generated by tools/setup-oracles.ps1 -- do not edit by hand.
# Oracles are black boxes: their source is never read.

date: $date
host: Windows $([System.Environment]::OSVersion.VersionString)

[libjxl]
path: $libjxlDir
revision: $rev
describe: $desc
cmake_flags: $($cmakeFlags -join ' ')
djxl_version: $djxlv
cjxl_version: $cjxlv

[jxl-oxide]
path: $oxide
version: $oxidev
"@ | Set-Content -Encoding utf8 (Join-Path $oracleBin "PINNED_REVISIONS.txt")

Log "done. Oracles in $oracleBin"
& (Join-Path $oracleBin "djxl.exe") --version
