import argparse
import hashlib
import importlib.util
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path


MODULE_PATH = Path(__file__).parents[1] / "codec_compare.py"
SPEC = importlib.util.spec_from_file_location("codec_compare", MODULE_PATH)
assert SPEC is not None and SPEC.loader is not None
codec_compare = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(codec_compare)


def ppm() -> bytes:
    return b"P6\n2 1\n255\n" + bytes((1, 2, 3, 4, 5, 6))


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


class CodecCompareTests(unittest.TestCase):
    def test_manifest_requires_hash_strata_and_provenance(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "source.ppm"
            source.write_bytes(ppm())
            manifest = root / "corpus.json"
            manifest.write_text(
                json.dumps(
                    {
                        "schema": codec_compare.CORPUS_SCHEMA,
                        "images": [
                            {
                                "id": "tiny",
                                "path": "source.ppm",
                                "sha256": digest(ppm()),
                                "strata": ["synthetic", "edge-flat"],
                                "provenance": "generated by unit test",
                            }
                        ],
                    }
                ),
                encoding="utf-8",
            )
            loaded = codec_compare.load_manifest(manifest)
            self.assertEqual((loaded["images"][0]["width"], loaded["images"][0]["height"]), (2, 1))
            loaded["images"][0]["sha256"] = "0" * 64
            manifest.write_text(json.dumps(loaded), encoding="utf-8")
            with self.assertRaisesRegex(codec_compare.HarnessError, "hash mismatch"):
                codec_compare.load_manifest(manifest)

    def test_counterbalanced_schedule_is_seeded_and_balanced(self):
        first = codec_compare.counterbalanced_schedule(17, 1234)
        second = codec_compare.counterbalanced_schedule(17, 1234)
        self.assertEqual(first, second)
        self.assertLessEqual(abs(first.count("A") - first.count("B")), 1)
        for offset in range(0, 16, 4):
            self.assertIn("".join(first[offset : offset + 4]), {"ABBA", "BAAB"})

    def test_interpolation_retains_the_bracket_and_monotonicity_is_explicit(self):
        result = codec_compare.interpolate([(10.0, 1.0), (20.0, 3.0)], 15.0)
        self.assertEqual(result["value"], 2.0)
        self.assertEqual(result["fraction"], 0.5)
        self.assertIsNone(codec_compare.interpolate([(10.0, 1.0), (20.0, 3.0)], 30.0))
        self.assertTrue(codec_compare.monotone([(1.0, 4.0), (2.0, 3.0)], increasing=False))
        self.assertFalse(codec_compare.monotone([(1.0, 4.0), (2.0, 5.0)], increasing=False))

    def test_metric_parser_handles_optional_perceptual_fields(self):
        metrics = codec_compare.metrics_from_output(
            "rmse=1 psnr_db=42.5 ssimulacra2=88.25 butteraugli=1.5 butteraugli_pnorm3=0.75"
        )
        self.assertEqual(metrics["ssimulacra2"], 88.25)
        self.assertEqual(metrics["butteraugli_pnorm3"], 0.75)
        self.assertIsNone(codec_compare.metrics_from_output("psnr_db=40")["ssimulacra2"])

    def test_rate_work_parser_keeps_nested_phase_counters(self):
        parsed = codec_compare.parse_named_counters(
            "rate_diag=fast_prices=2 structural_builds=2 anchor_fallbacks=0\n"
            "rate_plan_fast=plans=2 cover_ms=1.5\n"
            "rate_amp=search_amplification=1.25 writer_amplification=3.0\n"
        )
        self.assertEqual(parsed["rate_diag"]["structural_builds"], 2)
        self.assertEqual(parsed["rate_plan_fast"]["cover_ms"], 1.5)
        self.assertEqual(parsed["rate_amp"]["writer_amplification"], 3.0)

    def test_summarizer_refuses_a_non_monotone_quality_curve(self):
        records = self._curve_records([80.0, 82.0])
        summary, timing = codec_compare.summarize_records(records)
        self.assertFalse(summary["rows"][0]["cjxl_ssimulacra2_monotone"])
        self.assertEqual(timing["jobs"], [])

    def test_summarizer_keeps_codec_specific_settings(self):
        records = self._curve_records([90.0, 70.0])
        summary, timing = codec_compare.summarize_records(records)
        self.assertTrue(summary["rows"][0]["cjxl_ssimulacra2_monotone"])
        self.assertEqual(timing["jobs"][0]["jpxl"], {"bpp": 1.0})
        self.assertAlmostEqual(timing["jobs"][0]["cjxl"]["distance"], 1.5)

    def test_curve_subprocesses_keep_threads_and_presets_separate(self):
        if os.name == "nt":
            self.skipTest("the fake executable fixture uses POSIX shebang execution")
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "source.ppm"
            source.write_bytes(ppm())
            manifest = root / "corpus.json"
            manifest.write_text(
                json.dumps(
                    {
                        "schema": codec_compare.CORPUS_SCHEMA,
                        "images": [
                            {
                                "id": "tiny",
                                "path": str(source),
                                "sha256": digest(ppm()),
                                "strata": ["synthetic"],
                                "provenance": "unit test",
                            }
                        ],
                    }
                ),
                encoding="utf-8",
            )
            jpxl = self._write_tool(root / "jpxl", "jpxl")
            cjxl = self._write_tool(root / "cjxl", "cjxl")
            djxl = self._write_tool(root / "djxl", "djxl")
            args = argparse.Namespace(
                manifest=manifest,
                jpxl=jpxl,
                cjxl=cjxl,
                djxl=djxl,
                work_dir=root / "work",
                bpp=[1.0],
                distance=[1.5],
                threads=3,
                cjxl_threads=7,
                preset="fast",
                effort=8,
                max_additions=0,
            )
            records = codec_compare.curve_records(args)
            by_codec = {record["codec"]: record for record in records}
            self.assertEqual(by_codec["jpxl"]["setting"]["threads"], 3)
            self.assertEqual(by_codec["jpxl"]["setting"]["preset"], "fast")
            self.assertIsNone(by_codec["jpxl"]["setting"]["effort"])
            self.assertEqual(by_codec["cjxl"]["setting"]["threads"], 7)
            self.assertEqual(by_codec["cjxl"]["setting"]["effort"], 8)
            self.assertIsNone(by_codec["cjxl"]["setting"]["preset"])

    def test_refinement_suggests_the_widest_unresolved_bracket(self):
        records = self._curve_records([90.0, 70.0])
        own = [record for record in records if record["codec"] == "jpxl"]
        oracle = [record for record in records if record["codec"] == "cjxl"]
        suggestions = codec_compare.refinement_suggestions(own, oracle)
        self.assertGreater(len(suggestions), 0)
        self.assertIn(suggestions[0]["field"], {"bytes", "ssimulacra2", "butteraugli_pnorm3"})
        self.assertGreater(suggestions[0]["setting"], 1.0)
        self.assertLess(suggestions[0]["setting"], 2.0)

    @staticmethod
    def _write_tool(path: Path, kind: str) -> Path:
        script = f"""#!{sys.executable}
import pathlib, shutil, sys
if '--version' in sys.argv:
    print('{kind} fake 1')
elif '{kind}' == 'jpxl' and len(sys.argv) > 1 and sys.argv[1] == 'compare':
    print('psnr_db=40 ssimulacra2=80 butteraugli=2 butteraugli_pnorm3=1')
elif '{kind}' == 'jpxl':
    shutil.copyfile(sys.argv[-2], sys.argv[-1])
elif '{kind}' == 'cjxl':
    shutil.copyfile(sys.argv[1], sys.argv[2])
else:
    shutil.copyfile(sys.argv[1], sys.argv[2])
"""
        path.write_text(script, encoding="utf-8")
        path.chmod(0o755)
        return path

    @staticmethod
    def _curve_records(cjxl_ssim):
        common_input = {
            "id": "image",
            "path": "/image.ppm",
            "sha256": "a" * 64,
            "width": 8,
            "height": 8,
            "strata": ["test"],
            "provenance": "test",
        }

        def record(codec, setting, size, ssim, p3):
            return {
                "schema": codec_compare.RECORD_SCHEMA,
                "kind": "curve",
                "input": common_input,
                "codec": codec,
                "setting": {"value": setting},
                "rate_outcome": {"bytes": size},
                "metrics": {"ssimulacra2": ssim, "butteraugli_pnorm3": p3},
            }

        return [
            record("jpxl", 1.0, 150, 80.0, 1.0),
            record("cjxl", 1.0, 100, cjxl_ssim[0], 0.5),
            record("cjxl", 2.0, 200, cjxl_ssim[1], 1.5),
        ]


if __name__ == "__main__":
    unittest.main()
