import argparse
import hashlib
import importlib.util
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path


MODULE_PATH = Path(__file__).parents[1] / "codec_compare.py"
SPEC = importlib.util.spec_from_file_location("codec_compare", MODULE_PATH)
assert SPEC is not None and SPEC.loader is not None
codec_compare = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(codec_compare)


def ppm() -> bytes:
    return b"P6\n2 1\n255\n" + bytes((1, 2, 3, 4, 5, 6))


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


class CodecCompareTests(unittest.TestCase):
    def test_manifest_requires_hash_strata_and_provenance(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "source.ppm"
            source.write_bytes(ppm())
            manifest = root / "corpus.json"
            manifest.write_text(
                json.dumps(
                    {
                        "schema": codec_compare.CORPUS_SCHEMA,
                        "images": [
                            {
                                "id": "tiny",
                                "path": "source.ppm",
                                "sha256": digest(ppm()),
                                "strata": ["synthetic", "edge-flat"],
                                "provenance": "generated by unit test",
                            }
                        ],
                    }
                ),
                encoding="utf-8",
            )
            loaded = codec_compare.load_manifest(manifest)
            self.assertEqual((loaded["images"][0]["width"], loaded["images"][0]["height"]), (2, 1))
            loaded["images"][0]["sha256"] = "0" * 64
            manifest.write_text(json.dumps(loaded), encoding="utf-8")
            with self.assertRaisesRegex(codec_compare.HarnessError, "hash mismatch"):
                codec_compare.load_manifest(manifest)

    def test_counterbalanced_schedule_is_seeded_and_balanced(self):
        first = codec_compare.counterbalanced_schedule(17, 1234)
        second = codec_compare.counterbalanced_schedule(17, 1234)
        self.assertEqual(first, second)
        self.assertLessEqual(abs(first.count("A") - first.count("B")), 1)
        for offset in range(0, 16, 4):
            self.assertIn("".join(first[offset : offset + 4]), {"ABBA", "BAAB"})

    def test_interpolation_retains_the_bracket_and_monotonicity_is_explicit(self):
        result = codec_compare.interpolate([(10.0, 1.0), (20.0, 3.0)], 15.0)
        self.assertEqual(result["value"], 2.0)
        self.assertEqual(result["fraction"], 0.5)
        self.assertIsNone(codec_compare.interpolate([(10.0, 1.0), (20.0, 3.0)], 30.0))
        self.assertTrue(codec_compare.monotone([(1.0, 4.0), (2.0, 3.0)], increasing=False))
        self.assertFalse(codec_compare.monotone([(1.0, 4.0), (2.0, 5.0)], increasing=False))

    def test_metric_parser_handles_optional_perceptual_fields(self):
        metrics = codec_compare.metrics_from_output(
            "rmse=1 psnr_db=42.5 ssimulacra2_jpxl=88.5 ssimulacra2=88.25 "
            "butteraugli=1.5 butteraugli_pnorm3=0.75"
        )
        self.assertEqual(metrics["ssimulacra2_jpxl"], 88.5)
        self.assertEqual(metrics["ssimulacra2"], 88.25)
        self.assertEqual(metrics["butteraugli_pnorm3"], 0.75)
        self.assertIsNone(codec_compare.metrics_from_output("psnr_db=40")["ssimulacra2"])

    def test_rate_work_parser_keeps_nested_phase_counters(self):
        parsed = codec_compare.parse_named_counters(
            "rate_diag=fast_prices=2 structural_builds=2 anchor_fallbacks=0\n"
            "rate_plan_fast=plans=2 cover_ms=1.5\n"
            "rate_amp=search_amplification=1.25 writer_amplification=3.0\n"
        )
        self.assertEqual(parsed["rate_diag"]["structural_builds"], 2)
        self.assertEqual(parsed["rate_plan_fast"]["cover_ms"], 1.5)
        self.assertEqual(parsed["rate_amp"]["writer_amplification"], 3.0)

    def test_summarizer_refuses_a_non_monotone_quality_curve(self):
        records = self._curve_records([80.0, 82.0])
        summary, timing = codec_compare.summarize_records(records)
        self.assertFalse(summary["rows"][0]["cjxl_ssimulacra2_monotone"])
        self.assertEqual(timing["jobs"], [])

    def test_summarizer_keeps_codec_specific_settings(self):
        records = self._curve_records([90.0, 70.0])
        summary, timing = codec_compare.summarize_records(records)
        self.assertTrue(summary["rows"][0]["cjxl_ssimulacra2_monotone"])
        self.assertEqual(timing["jobs"][0]["jpxl"], {"bpp": 1.0})
        self.assertAlmostEqual(timing["jobs"][0]["cjxl"]["distance"], 1.5)

    def test_curve_subprocesses_keep_threads_and_presets_separate(self):
        if os.name == "nt":
            self.skipTest("the fake executable fixture uses POSIX shebang execution")
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "source.ppm"
            source.write_bytes(ppm())
            manifest = root / "corpus.json"
            manifest.write_text(
                json.dumps(
                    {
                        "schema": codec_compare.CORPUS_SCHEMA,
                        "images": [
                            {
                                "id": "tiny",
                                "path": str(source),
                                "sha256": digest(ppm()),
                                "strata": ["synthetic"],
                                "provenance": "unit test",
                            }
                        ],
                    }
                ),
                encoding="utf-8",
            )
            jpxl = self._write_tool(root / "jpxl", "jpxl")
            cjxl = self._write_tool(root / "cjxl", "cjxl")
            djxl = self._write_tool(root / "djxl", "djxl")
            args = argparse.Namespace(
                manifest=manifest,
                jpxl=jpxl,
                cjxl=cjxl,
                djxl=djxl,
                work_dir=root / "work",
                bpp=[1.0],
                distance=[1.5],
                threads=3,
                cjxl_threads=7,
                preset="fast",
                effort=8,
                max_additions=0,
            )
            records = codec_compare.curve_records(args)
            by_codec = {record["codec"]: record for record in records}
            self.assertEqual(by_codec["jpxl"]["setting"]["threads"], 3)
            self.assertEqual(by_codec["jpxl"]["setting"]["preset"], "fast")
            self.assertIsNone(by_codec["jpxl"]["setting"]["effort"])
            self.assertEqual(by_codec["cjxl"]["setting"]["threads"], 7)
            self.assertEqual(by_codec["cjxl"]["setting"]["effort"], 8)
            self.assertIsNone(by_codec["cjxl"]["setting"]["preset"])

    def test_refinement_suggests_the_widest_unresolved_bracket(self):
        records = self._curve_records([90.0, 70.0])
        own = [record for record in records if record["codec"] == "jpxl"]
        oracle = [record for record in records if record["codec"] == "cjxl"]
        suggestions = codec_compare.refinement_suggestions(own, oracle)
        self.assertGreater(len(suggestions), 0)
        self.assertIn(suggestions[0]["field"], {"bytes", "ssimulacra2", "butteraugli_pnorm3"})
        self.assertGreater(suggestions[0]["setting"], 1.0)
        self.assertLess(suggestions[0]["setting"], 2.0)

    def test_ppm_loader_preserves_whitespace_valued_first_sample(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "leading-newline.ppm"
            path.write_bytes(b"P6\n1 1\n255\n" + bytes((10, 20, 30)))
            image = codec_compare.load_ppm(path)
            expected = (0.2126 * 10 + 0.7152 * 20 + 0.0722 * 30) / 255
            self.assertAlmostEqual(codec_compare.ppm_luma(image, 0, 0), expected)

    def test_risk_weight_fit_uses_ranked_training_labels(self):
        training = []
        validation = []
        for index in range(100):
            features = [index / 99, 0.5, 0.5, 0.5]
            training.append({"features": features, "label": float(index)})
            validation.append({"features": features, "label": float(99 - index)})
        weights = codec_compare.choose_risk_weights([training])
        self.assertEqual(weights, (1, 0, 0, 0))
        self.assertEqual(codec_compare.risk_recall(training, weights, 10), 1.0)
        self.assertEqual(codec_compare.risk_recall(validation, weights, 10), 0.0)

    def test_quality_line_parser(self):
        line = (
            "quality_target=85.0000 achieved=85.1372 bytes=412883 "
            "metric=ssimulacra2-jpxl-1 effort=balanced probes=3 prices=2 status=met"
        )
        parsed = codec_compare.parse_quality_line("startup noise\n" + line + "\ntrailing")
        self.assertEqual(parsed["requested_score"], 85.0)
        self.assertAlmostEqual(parsed["achieved_score"], 85.1372)
        self.assertEqual(parsed["bytes"], 412883)
        self.assertEqual(parsed["metric"], "ssimulacra2-jpxl-1")
        self.assertEqual(parsed["effort"], "balanced")
        self.assertEqual(parsed["probes"], 3)
        self.assertEqual(parsed["prices"], 2)
        self.assertEqual(parsed["status"], "met")
        with self.assertRaises(codec_compare.HarnessError):
            codec_compare.parse_quality_line("no perceptual line at all")

    def test_curve_rejects_bpp_and_quality_together(self):
        parser = codec_compare.build_parser()
        common = [
            "curve", "--manifest", "m", "--output", "o", "--work-dir", "w",
            "--jpxl", "j", "--cjxl", "c", "--djxl", "d",
        ]
        with self.assertRaises(SystemExit):
            parser.parse_args(common + ["--bpp", "1.0", "--quality", "85"])
        # --quality alone parses even though --bpp carries a default value.
        args = parser.parse_args(common + ["--quality", "85", "90"])
        self.assertEqual(args.quality, [85.0, 90.0])
        self.assertIsNone(args.image_id)
        self.assertEqual(args.quality_effort, "balanced")
        self.assertEqual(args.rate_bpp, list(codec_compare.DEFAULT_QUALITY_RATE_BPPS))
        self.assertTrue(args.quality_trace)
        args = parser.parse_args(
            common
            + [
                "--quality",
                "85",
                "--rate-bpp",
                "0.25,0.75",
                "--no-quality-trace",
            ]
        )
        self.assertEqual(args.rate_bpp, [0.25, 0.75])
        self.assertFalse(args.quality_trace)
        with self.assertRaises(SystemExit):
            parser.parse_args(common + ["--quality", "150"])

    def test_quality_trace_reader(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "trace.jsonl"
            path.write_text(
                json.dumps({"schema": "other/1"}) + "\n"
                + json.dumps(
                    {
                        "schema": codec_compare.QUALITY_TRACE_SCHEMA,
                        "requested_score": 85.0,
                        "achieved_score": 85.1,
                        "wall_by_phase": {
                            "analysis": 1.0, "plan": 2.0, "render": 3.0,
                            "metric": 4.0, "entropy": 5.0, "emit": 6.0,
                        },
                        "probes": [],
                    }
                )
                + "\n",
                encoding="utf-8",
            )
            trace = codec_compare.read_quality_trace(path)
            self.assertEqual(trace["wall_by_phase"]["render"], 3.0)

    def test_quality_curve_merges_line_and_trace(self):
        if os.name == "nt":
            self.skipTest("the fake executable fixture uses POSIX shebang execution")
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "source.ppm"
            source.write_bytes(ppm())
            manifest = root / "corpus.json"
            manifest.write_text(
                json.dumps(
                    {
                        "schema": codec_compare.CORPUS_SCHEMA,
                        "images": [
                            {
                                "id": "tiny",
                                "path": str(source),
                                "sha256": digest(ppm()),
                                "strata": ["synthetic"],
                                "provenance": "unit test",
                            }
                        ],
                    }
                ),
                encoding="utf-8",
            )
            jpxl = self._write_quality_tool(root / "jpxl")
            cjxl = self._write_tool(root / "cjxl", "cjxl")
            djxl = self._write_tool(root / "djxl", "djxl")
            args = argparse.Namespace(
                manifest=manifest, jpxl=jpxl, cjxl=cjxl, djxl=djxl,
                work_dir=root / "work", bpp=None, quality=[85.0],
                distance=[1.0, 2.0], threads=4, cjxl_threads=4,
                preset="balanced", effort=7, max_additions=0,
                quality_effort="balanced", quality_trace=True,
                rate_bpp=[0.5, 1.0],
                image_id=["tiny"],
            )
            records = codec_compare.curve_records(args)
            own = [
                r
                for r in records
                if r["codec"] == "jpxl" and r["setting"]["kind"] == "quality"
            ][0]
            rate = [
                r
                for r in records
                if r["codec"] == "jpxl" and r["setting"]["kind"] == "bpp"
            ]
            self.assertEqual(own["setting"]["kind"], "quality")
            self.assertEqual(own["setting"]["effort"], "balanced")
            self.assertEqual(own["requested_score"], 85.0)
            self.assertAlmostEqual(own["achieved_score"], 85.2)
            self.assertEqual(own["quality_status"], "met")
            self.assertEqual(own["probes"], 3)
            self.assertEqual(own["prices"], 2)
            self.assertIn("--quality", own["command"])
            self.assertEqual(own["metrics"]["ssimulacra2_jpxl"], 85.5)
            self.assertEqual(own["wall_by_phase"]["emit"], 6.0)
            self.assertEqual(own["structural_builds"], 1)
            self.assertTrue(own["trace_path"].endswith(".trace.jsonl"))
            self.assertEqual(len(rate), 2)
            self.assertEqual([row["setting"]["value"] for row in rate], [0.5, 1.0])
            self.assertTrue(
                all(row["setting"]["preset"] == "balanced" for row in rate)
            )
            self.assertTrue(
                all(
                    row["setting"]["role"] == "quality_rate_baseline"
                    for row in rate
                )
            )

            args.image_id = ["missing"]
            with self.assertRaisesRegex(codec_compare.HarnessError, "missing"):
                codec_compare.curve_records(args)

    def test_bd_rate_constant_ratio_has_known_answer(self):
        reference = [(score, 1000.0 * (10.0 ** (-0.01 * score))) for score in (50, 60, 70, 80, 90)]
        test = [(score, 2.0 * byte_count) for score, byte_count in reference]
        result = codec_compare.bd_rate(reference, test)
        self.assertIsNotNone(result)
        self.assertAlmostEqual(result, 100.0, places=4)
        self.assertIsNone(codec_compare.bd_rate(reference[:3], test[:3]))

    def test_matched_score_interpolation_is_linear_in_log_rate(self):
        rate = [
            self._rate_record(0.5, 100, 80.0),
            self._rate_record(1.0, 400, 90.0),
        ]
        match = codec_compare.interpolate_metric_records(
            rate,
            codec_compare.PRIMARY_QUALITY_METRIC,
            85.0,
            increasing_with_setting=True,
            log_rate=True,
        )
        self.assertIsNotNone(match)
        self.assertAlmostEqual(match["value"], 200.0)
        self.assertEqual(match["interpolation"], "log-bytes-linear-in-metric")

    def test_quality_summary_detects_floor_and_monotonicity(self):
        cjxl_records = [
            self._cjxl_record(0.5, 300, 95.0),
            self._cjxl_record(1.0, 200, 90.0),
            self._cjxl_record(2.0, 100, 80.0),
        ]
        jpxl_quality = [
            self._quality_record(85.0, 85.5, 180),
            self._quality_record(90.0, 90.2, 220),
            self._quality_record(95.0, 94.0, 260),
        ]
        # The controller and common-reference implementations are parity-bounded,
        # not bit-identical. Curve matching must stay on the common decoded axis.
        jpxl_quality[0]["metrics"][codec_compare.PRIMARY_QUALITY_METRIC] = 84.0
        jpxl_rate = [
            self._rate_record(0.5, 100, 80.0),
            self._rate_record(1.0, 200, 90.0),
            self._rate_record(2.0, 400, 95.0),
            self._rate_record(3.0, 800, 98.0),
        ]
        summary = codec_compare.quality_image_summary(
            "img", jpxl_quality, cjxl_records, 0.5, jpxl_rate=jpxl_rate
        )
        self.assertEqual(summary["floor_violations"], 1)
        self.assertTrue(summary["achieved_monotone_in_requested"])
        self.assertTrue(summary["bytes_monotone_in_requested"])
        self.assertAlmostEqual(summary["targets"][0]["overshoot"], 0.5)
        self.assertFalse(summary["targets"][0]["floor_violation"])
        self.assertTrue(summary["targets"][2]["floor_violation"])
        self.assertAlmostEqual(summary["targets"][0]["comparison_score"], 84.0)
        self.assertAlmostEqual(summary["targets"][0]["reference_score"], 85.0)
        self.assertAlmostEqual(summary["targets"][0]["matched_jpxl_rate_bpp"], 0.7)
        self.assertIsNotNone(summary["targets"][0]["byte_ratio_vs_jpxl_rate"])
        self.assertIsNotNone(summary["targets"][0]["byte_ratio_vs_cjxl"])
        self.assertEqual(summary["coverage"]["jpxl_rate"]["matched"], 3)

        missing_reference = [self._quality_record(85.0, 85.5, 180)]
        missing_reference[0]["metrics"][codec_compare.PRIMARY_QUALITY_METRIC] = None
        inconclusive = codec_compare.quality_image_summary(
            "img", missing_reference, cjxl_records, 0.0, jpxl_rate=jpxl_rate
        )
        self.assertEqual(
            inconclusive["targets"][0]["jpxl_rate_match_status"],
            "quality_metric_unavailable",
        )
        self.assertIsNone(inconclusive["targets"][0]["byte_ratio_vs_jpxl_rate"])

        substituted = [self._quality_record(95.0, 94.0, 260)]
        substituted[0]["comparison_score_source"] = "controller_substitution"
        sensitivity = codec_compare.quality_image_summary(
            "img", substituted, cjxl_records, 0.5, jpxl_rate=jpxl_rate
        )
        self.assertTrue(sensitivity["targets"][0]["floor_violation"])
        self.assertIsNone(sensitivity["targets"][0]["decoded_floor_violation"])
        self.assertEqual(sensitivity["decoded_floor_violations"], 0)

        non_monotone = [
            self._quality_record(85.0, 90.0, 180),
            self._quality_record(90.0, 88.0, 220),
        ]
        broken = codec_compare.quality_image_summary(
            "img", non_monotone, cjxl_records, 0.0, jpxl_rate=jpxl_rate
        )
        self.assertFalse(broken["achieved_monotone_in_requested"])

    def test_quality_summary_and_markdown_via_summarize(self):
        records = [
            self._cjxl_record(0.5, 300, 95.0),
            self._cjxl_record(1.0, 200, 90.0),
            self._cjxl_record(2.0, 100, 80.0),
            self._rate_record(0.5, 100, 80.0),
            self._rate_record(1.0, 200, 90.0),
            self._rate_record(2.0, 400, 95.0),
            self._rate_record(3.0, 800, 98.0),
            self._quality_record(85.0, 85.5, 180),
            self._quality_record(90.0, 90.2, 220),
            self._quality_record(95.0, 94.0, 260),
        ]
        summary, plan = codec_compare.summarize_records(records, score_guard=0.5)
        self.assertIn("quality", summary)
        self.assertEqual(summary["quality"]["aggregate"]["floor_violation_count"], 1)
        self.assertEqual(
            summary["quality"]["aggregate"]["decoded_floor_violation_count"], 1
        )
        self.assertEqual(summary["quality"]["images"][0]["decoded_floor_violations"], 1)
        self.assertEqual(summary["quality"]["aggregate"]["probe_distribution"], {"3": 3})
        self.assertEqual(summary["quality"]["schema"], codec_compare.QUALITY_SUMMARY_SCHEMA)
        self.assertGreater(summary["quality"]["aggregate"]["coverage"]["jpxl_rate"]["matched"], 0)
        self.assertEqual(summary["quality"]["aggregate"]["budget_overage_count"], 0)
        self.assertEqual(
            summary["quality"]["aggregate"]["comparison_score_source_distribution"],
            {"decoded_pair": 3},
        )
        self.assertGreater(len(summary["rows"]), 0)
        self.assertGreater(len(plan["jobs"]), 0)
        markdown = codec_compare.render_quality_markdown(summary)
        self.assertIn("## img", markdown)
        self.assertIn("BD-rate: vs JPXL rate", markdown)
        self.assertIn("JPXL rate matched-score coverage", markdown)
        self.assertIn("decoded in-tree floor violations", markdown)
        self.assertIn("| requested |", markdown)

    def test_metric_variation_aggregation(self):
        pairs = [
            {"id": "a", "scores": [80.0, 80.3, 80.1]},
            {"id": "b", "scores": [75.0, 75.02]},
        ]
        report = codec_compare.aggregate_metric_variation(pairs)
        self.assertAlmostEqual(report["pairs"][0]["max_abs_delta"], 0.3, places=6)
        self.assertAlmostEqual(report["overall_max_abs_delta"], 0.3, places=6)
        self.assertAlmostEqual(report["score_guard"], 0.6, places=6)
        self.assertIn("ceil_1e-2", report["guard_formula"])
        self.assertAlmostEqual(codec_compare.ceil_to_hundredth(0.611), 0.62, places=6)

    @staticmethod
    def _cjxl_record(setting, size, ssim):
        return {
            "schema": codec_compare.RECORD_SCHEMA,
            "kind": "curve",
            "codec": "cjxl",
            "input": {"id": "img"},
            "setting": {"kind": "distance", "value": setting},
            "rate_outcome": {"bytes": size, "bpp": size / 100.0},
            "metrics": {
                "ssimulacra2_jpxl": ssim,
                "ssimulacra2": ssim,
                "butteraugli_pnorm3": setting,
            },
        }

    @staticmethod
    def _quality_record(requested, achieved, size):
        return {
            "schema": codec_compare.RECORD_SCHEMA,
            "kind": "curve",
            "codec": "jpxl",
            "input": {"id": "img"},
            "setting": {
                "kind": "quality",
                "value": requested,
                "effort": "balanced",
            },
            "rate_outcome": {"bytes": size, "bpp": size / 100.0},
            "metrics": {
                "ssimulacra2_jpxl": achieved,
                "ssimulacra2": achieved - 0.5,
                "butteraugli_pnorm3": None,
            },
            "requested_score": requested,
            "achieved_score": achieved,
            "quality_status": "met",
            "probes": 3,
            "prices": 2,
            "structural_builds": 1,
        }

    @staticmethod
    def _rate_record(setting, size, ssim):
        return {
            "schema": codec_compare.RECORD_SCHEMA,
            "kind": "curve",
            "codec": "jpxl",
            "input": {"id": "img"},
            "setting": {
                "kind": "bpp",
                "value": setting,
                "preset": "balanced",
                "threads": 4,
                "role": "quality_rate_baseline",
            },
            "rate_outcome": {"bytes": size, "bpp": size / 100.0},
            "metrics": {
                "ssimulacra2_jpxl": ssim,
                "ssimulacra2": ssim - 0.5,
                "butteraugli_pnorm3": None,
            },
        }

    @staticmethod
    def _write_quality_tool(path: Path) -> Path:
        script = f"""#!{sys.executable}
import json, os, pathlib, shutil, sys
argv = sys.argv
if '--version' in argv:
    print('jpxl fake 1')
elif len(argv) > 1 and argv[1] == 'compare':
    print('psnr_db=40 ssimulacra2_jpxl=85.5 ssimulacra2=85.0 '
          'butteraugli=2 butteraugli_pnorm3=1')
elif len(argv) > 1 and argv[1] == 'encode':
    src, out = argv[-2], argv[-1]
    shutil.copyfile(src, out)
    if '--quality' in argv:
        requested = float(argv[argv.index('--quality') + 1])
        achieved = requested + 0.2
        size = pathlib.Path(out).stat().st_size
        print(
            'quality_target=%.4f achieved=%.4f bytes=%d metric=ssimulacra2-jpxl-1 '
            'effort=balanced probes=3 prices=2 status=met' % (requested, achieved, size)
        )
        trace = os.environ.get('JPXL_QUALITY_TRACE')
        if trace:
            with open(trace, 'w') as handle:
                handle.write(json.dumps({{
                    'schema': 'jpxl.quality-trace/1',
                    'requested_score': requested,
                    'achieved_score': achieved,
                    'final_exact_bytes': size,
                    'pixel_probes': 3,
                    'exact_prices': 2,
                    'structural_builds': 1,
                    'status': 'met',
                    'wall_by_phase': {{
                        'analysis': 1.0, 'plan': 2.0, 'render': 3.0,
                        'metric': 4.0, 'entropy': 5.0, 'emit': 6.0,
                    }},
                    'probes': [],
                }}) + '\\n')
else:
    shutil.copyfile(argv[-2], argv[-1])
"""
        path.write_text(script, encoding="utf-8")
        path.chmod(0o755)
        return path

    @staticmethod
    def _write_tool(path: Path, kind: str) -> Path:
        script = f"""#!{sys.executable}
import pathlib, shutil, sys
if '--version' in sys.argv:
    print('{kind} fake 1')
elif '{kind}' == 'jpxl' and len(sys.argv) > 1 and sys.argv[1] == 'compare':
    print('psnr_db=40 ssimulacra2_jpxl=80.5 ssimulacra2=80 '
          'butteraugli=2 butteraugli_pnorm3=1')
elif '{kind}' == 'jpxl':
    shutil.copyfile(sys.argv[-2], sys.argv[-1])
elif '{kind}' == 'cjxl':
    shutil.copyfile(sys.argv[1], sys.argv[2])
else:
    shutil.copyfile(sys.argv[1], sys.argv[2])
"""
        path.write_text(script, encoding="utf-8")
        path.chmod(0o755)
        return path

    @staticmethod
    def _curve_records(cjxl_ssim):
        common_input = {
            "id": "image",
            "path": "/image.ppm",
            "sha256": "a" * 64,
            "width": 8,
            "height": 8,
            "strata": ["test"],
            "provenance": "test",
        }

        def record(codec, setting, size, ssim, p3):
            return {
                "schema": codec_compare.RECORD_SCHEMA,
                "kind": "curve",
                "input": common_input,
                "codec": codec,
                "setting": {"value": setting},
                "rate_outcome": {"bytes": size},
                "metrics": {"ssimulacra2": ssim, "butteraugli_pnorm3": p3},
            }

        return [
            record("jpxl", 1.0, 150, 80.0, 1.0),
            record("cjxl", 1.0, 100, cjxl_ssim[0], 0.5),
            record("cjxl", 2.0, 200, cjxl_ssim[1], 1.5),
        ]


if __name__ == "__main__":
    unittest.main()
